Generate new dockerfile if it do not exist for the choosen distro.

diff --git a/bin/start_ros b/bin/start_ros
--- a/bin/start_ros
+++ b/bin/start_ros
@@ -5,11 +5,14 @@ SCRIPT_PATH=$(realpath "$0")
 PROJECT_ROOT=$(dirname "$(dirname "$SCRIPT_PATH")")
 
 if [ -z $ROS_DOCKER_DISTRO ]; then
-    export ROS_DOCKER_DISTRO="noetic"
+    echo "Error: ROS_DOCKER_DISTRO is not set. Please set it and try again.";
+    exit 1;
+    # export ROS_DOCKER_DISTRO="noetic"
 fi
 
-if [ -z $ROS_DOCKER_VERSION ]; then
-    export ROS_DOCKER_VERSION="ros"
+if [ ! -f $PROJECT_ROOT/ros-images/$ROS_DOCKER_DISTRO/Dockerfile ]; then
+    echo "Did not find dockerfile for $ROS_DOCKER_DISTRO locally.";
+    cd $PROJECT_ROOT && make generate-dockerfile;
 fi
 
 export UID=$(id -u)
@@ -22,11 +25,13 @@ export XAUTH=/tmp/.ros_in_docker.xauth
 touch $XAUTH
 xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
 
-# Save container name
-DOCKER_CONTAINER_NAME=${ROS_DOCKER_VERSION}-${ROS_DOCKER_DISTRO}-container
+# Save container name FIXME: change to version instead of container name?
+DOCKER_CONTAINER_NAME="ros-${ROS_DOCKER_DISTRO}-container"
 
+# TODO: this solution does not allow multiple containers to run simultaneously
 echo $DOCKER_CONTAINER_NAME > "${PROJECT_ROOT}/.ros-version"
+
+echo "starting container $DOCKER_CONTAINER_NAME"
 
 docker compose -f "${PROJECT_ROOT}/compose.yaml" up
 
-# TODO: clean up XAUTH and container?
